/**
 * The two ExtendScript generators.
 *
 * The split is the one Kyle asked for, and it is a build/link split rather than two unrelated
 * exporters:
 *
 *   PACKAGE  every catalogue asset becomes its own comp, saved once into a standalone
 *            `Win95Assets.aep`. Expensive, run rarely.
 *   SCENE    a layout becomes a scene comp whose layers *reference* comps from that package.
 *            Cheap, run constantly.
 *
 * The mechanism underneath is `project.save(file)` on one side and `importFile` with
 * `ImportAsType.PROJECT` on the other — the AE spike proved that round trip: a saved `.aep`
 * re-imports into a different project as a single folder containing every comp intact.
 *
 * Both scripts are ES3, both embed their data as object literals (there is no `JSON` in
 * ExtendScript), and both share `ES3_RUNTIME`.
 */

import { toRgb } from '../assets/colors'
import { mergeRuns, parseRuns } from '../assets/svgPath'
import {
  CLOSE_GLYPH,
  WINDOW_CHROME,
  WIN95_COLORS,
  WIN95_FONT,
  closeButtonRects,
  windowFrameRects,
  type ChromeRect,
} from '../assets/chrome'
import type { IconGeometry } from '../assets/catalog'
import type { Scene } from '../scene/types'
import { es3Literal, type Es3Value } from './es3'
import { ES3_RUNTIME } from './runtime'

/** Comp name for a catalogue asset. The scene script resolves package comps by this exact name. */
export function assetCompName(assetId: string): string {
  return `Icon - ${assetId}`
}

/** Folder the package builds into, and the folder the scene script looks inside. */
export const PACKAGE_FOLDER = 'Win95 Assets'

/** Rectangles grouped by colour, in the compact shape the ES3 runtime consumes. */
type EmittedLayer = { k: string; c: readonly number[]; r: number[][] }

function emitChromeLayers(rects: ChromeRect[]): EmittedLayer[] {
  // One AE group per colour rather than per rectangle: far fewer groups, and it matches how the
  // icon geometry is already organised, so the runtime needs only one code path.
  const byColor = new Map<string, number[][]>()
  for (const rect of rects) {
    const bucket = byColor.get(rect.color)
    if (bucket) bucket.push([rect.x, rect.y, rect.w, rect.h])
    else byColor.set(rect.color, [[rect.x, rect.y, rect.w, rect.h]])
  }
  return [...byColor.entries()].map(([color, r]) => ({ k: color, c: toRgb(color), r }))
}

function emitIconLayers(icon: IconGeometry): EmittedLayer[] {
  return icon.layers.map((layer) => ({
    k: layer.color,
    c: toRgb(layer.color),
    r: layer.rects.map((rect) => [rect.x, rect.y, rect.w, rect.h]),
  }))
}

function header(title: string, extra: string[] = []): string {
  const lines = [
    `// ${title}`,
    '//',
    '// Generated by the Windows 95 Asset Studio. Do not edit by hand - re-export instead.',
    `// Generated ${new Date().toISOString()}`,
    '//',
    ...extra.map((line) => `// ${line}`),
    '',
    '#target aftereffects',
  ]
  return lines.join('\n')
}

// ---------------------------------------------------------------------------- package

export type PackageOptions = {
  /** Comp frame rate and duration. Static assets still need both. */
  fps?: number
  durationSeconds?: number
  /** File name written into the chosen folder. */
  fileName?: string
}

/**
 * Build the package script: one comp per asset, saved as a standalone `.aep`.
 *
 * Two things make this bearable at catalogue scale. The geometry has already been merged from
 * pixel runs into rectangles (~30% fewer shapes, losslessly), and identical artwork is exported
 * once — 1536 catalogue entries reduce to 1043 distinct images, because @react95/icons ships the
 * same bitmap under several names. Aliases are recorded so the scene script can resolve any name
 * to the comp that was actually built.
 */
export function buildPackageScript(icons: IconGeometry[], options: PackageOptions = {}): string {
  const fps = options.fps ?? 30
  const duration = options.durationSeconds ?? 10
  const fileName = options.fileName ?? 'Win95Assets.aep'

  // Deduplicate by geometry. @react95/icons ships a lot of the same artwork under different
  // names — 1517 drawable entries reduce to 1037 distinct images — so one comp can hold the
  // shapes for all of its names.
  //
  // The alias map is keyed and valued by **comp name**, not asset id. That matters: the scene
  // script resolves everything by comp name, and if an alias pointed at a bare asset id the
  // package would build a comp the scene could never find. Every catalogue name still ends up
  // with its own comp (see the alias-comp loop in the script) — the geometry is shared, the
  // identity is not.
  const seen = new Map<string, string>() // signature -> comp name that owns the geometry
  const unique: IconGeometry[] = []
  const aliases: Record<string, string> = {}

  for (const icon of icons) {
    const signature = JSON.stringify(emitIconLayers(icon))
    const owner = seen.get(signature)
    if (owner) {
      aliases[assetCompName(icon.asset.id)] = owner
    } else {
      seen.set(signature, assetCompName(icon.asset.id))
      unique.push(icon)
    }
  }

  const assets: Es3Value = unique.map((icon) => ({
    n: assetCompName(icon.asset.id),
    w: icon.asset.width,
    h: icon.asset.height,
    l: emitIconLayers(icon) as unknown as Es3Value,
  }))

  const totalShapes = unique.reduce((sum, icon) => sum + icon.shapeCount, 0)

  return `${header('Windows 95 asset package - every asset as its own comp', [
    `${icons.length} catalogue assets -> ${unique.length} comps (${
      icons.length - unique.length
    } are duplicate artwork)`,
    `${totalShapes} shape rectangles after lossless run merging`,
    '',
    'Run: File > Scripts > Run Script File, then choose an output folder.',
    'This builds into a NEW project and saves the .aep; your open project is left alone',
    '(you will be prompted to save it if it has unsaved changes).',
  ])}

${ES3_RUNTIME}

var FPS = ${fps};
var DURATION = ${duration};
var FILENAME = ${es3Literal(fileName)};
var FOLDER_NAME = ${es3Literal(PACKAGE_FOLDER)};

// Every asset: n = comp name, w/h = size, l = one entry per colour with pre-computed RGB.
var ASSETS = ${es3Literal(assets)};

// Comp name -> comp name whose artwork is byte-identical. Each of these still gets its own
// comp; it just holds one layer of the shared original instead of its own copy of the shapes.
var ALIASES = ${es3Literal(aliases as unknown as Es3Value)};

function main() {
    var started = new Date();
    var outDir = Folder.selectDialog("Choose a folder to save " + FILENAME + " into");
    if (outDir === null) { return; }

    app.newProject();
    app.beginUndoGroup("Build Win95 asset package");
    var suppressed = suppressRefresh(true);

    log("package build " + started.toString());
    log("app.version=" + app.version + " suppressPanelRefresh=" + suppressed);

    var root = app.project.items.addFolder(FOLDER_NAME);
    var icons = app.project.items.addFolder("Icons");
    icons.parentFolder = root;

    // Keep the built comps in a lookup as we go. Scanning app.project.items for each alias
    // would be O(aliases x items) -- around 500 x 1500 on a full catalogue build.
    var byName = {};
    var shapes = 0;
    for (var i = 0; i < ASSETS.length; i++) {
        var built = buildAssetComp(icons, ASSETS[i], FPS, DURATION);
        byName[ASSETS[i].n] = built.comp;
        shapes += built.shapes;
    }
    log("built " + ASSETS.length + " comps, " + shapes + " shapes");

    // Every duplicate name still gets its own comp, holding a single layer of the original.
    // That costs one comp and one layer instead of re-drawing the shapes, and it means the
    // scene script can resolve any catalogue name without knowing aliasing exists.
    var aliasCount = 0;
    for (var key in ALIASES) {
        if (!ALIASES.hasOwnProperty(key)) { continue; }
        var owner = byName[ALIASES[key]];
        if (owner === undefined) { log("alias owner missing: " + ALIASES[key]); continue; }
        var aliasComp = app.project.items.addComp(key, owner.width, owner.height, 1.0, DURATION, FPS);
        aliasComp.parentFolder = icons;
        aliasComp.layers.add(owner).name = ALIASES[key];
        aliasCount++;
    }
    log("aliases: " + aliasCount + " names share artwork via a one-layer comp");

    if (suppressed) { suppressRefresh(false); }
    app.endUndoGroup();

    var aep = new File(outDir.fsName + "/" + FILENAME);
    app.project.save(aep);

    var ms = (new Date()).getTime() - started.getTime();
    log("saved " + aep.fsName + " (" + aep.length + " bytes) in " + ms + " ms");
    log("shapes per second: " + Math.round(shapes / (ms / 1000)));
    writeLog(outDir, "win95-package-log.txt");

    alert("Asset package built.\\n\\n" +
          ASSETS.length + " comps, " + shapes + " shapes\\n" +
          Math.round(ms / 1000) + " seconds\\n\\n" +
          aep.fsName +
          "\\n\\nImport this into any project with File > Import > File.");
}

try { main(); }
catch (err) { alert("Package export FAILED\\n" + err.toString() + "\\nline " + err.line + "\\n\\n" + LOG.join("\\n")); }
`
}

// ---------------------------------------------------------------------------- scene

export type SceneOptions = {
  /**
   * Assets the scene needs, so the script can name precisely what is missing when the package
   * has not been imported yet.
   */
  requiredAssetIds: string[]
}

/**
 * Build the scene script: window precomps drawn from the chrome registry, plus layers that
 * reference the package's asset comps.
 *
 * Window comps are built here rather than pre-baked into the package because their geometry
 * depends on the size the user dragged them to — a package cannot enumerate every possible
 * window size. Their title-bar icons still reference package comps, so "every asset is its own
 * comp" holds throughout.
 */
export function buildSceneScript(scene: Scene, options: SceneOptions): string {
  const closeGlyphRects = mergeRuns(parseRuns(CLOSE_GLYPH)).map((r) => [r.x, r.y, r.w, r.h])

  // Windows are emitted back-to-front so the script can add layers in order and let each new
  // layer land on top, which avoids any moveBefore/moveAfter juggling.
  const windows = [...scene.windows].sort((a, b) => a.z - b.z)

  const emittedWindows: Es3Value = windows.map((win) => {
    const button = closeButtonRects(win.width)
    return {
      id: win.id,
      title: win.title,
      icon: win.iconAssetId ? assetCompName(win.iconAssetId) : null,
      x: win.x,
      y: win.y,
      w: win.width,
      h: win.height,
      // Frame and button share one shape layer per colour group.
      frame: emitChromeLayers([...windowFrameRects(win.width, win.height, win.active), ...button.rects]) as unknown as Es3Value,
      glyph: { x: button.glyph.x, y: button.glyph.y, r: closeGlyphRects },
      iconPos: { x: WINDOW_CHROME.iconOffset.x, y: WINDOW_CHROME.iconOffset.y },
      textX: WINDOW_CHROME.titleTextX,
      textBaseline: WINDOW_CHROME.titleBaselineY,
    }
  })

  const emittedIcons: Es3Value = scene.icons.map((icon) => ({
    comp: assetCompName(icon.assetId),
    x: icon.x,
    y: icon.y,
    label: icon.label,
  }))

  return `${header(`Windows 95 scene - ${scene.name}`, [
    `${scene.windows.length} windows, ${scene.icons.length} placed icons`,
    `${scene.width}x${scene.height} @ ${scene.fps}fps`,
    '',
    'Requires the asset package. Import Win95Assets.aep first, or let this script',
    'prompt you for it. Run with File > Scripts > Run Script File.',
  ])}

${ES3_RUNTIME}

var SCENE = ${es3Literal({
    name: scene.name,
    w: scene.width,
    h: scene.height,
    fps: scene.fps,
    duration: scene.durationSeconds,
    bg: [...toRgb(scene.background)],
    taskbar: scene.showTaskbar,
  } as unknown as Es3Value)};

var FONT_PS = ${es3Literal(WIN95_FONT.postScriptName)};
var TITLE_SIZE = ${WIN95_FONT.titleSize};
var TITLE_RGB = ${es3Literal([...toRgb(WIN95_COLORS.titleText)] as unknown as Es3Value)};
var GLYPH_RGB = ${es3Literal([...toRgb(WIN95_COLORS.darkest)] as unknown as Es3Value)};
var TASKBAR_RGB = ${es3Literal([...toRgb(WIN95_COLORS.face)] as unknown as Es3Value)};
var TASKBAR_H = 28;

var WINDOWS = ${es3Literal(emittedWindows)};
var ICONS = ${es3Literal(emittedIcons)};
var REQUIRED = ${es3Literal(options.requiredAssetIds.map(assetCompName) as unknown as Es3Value)};

// Resolve every asset comp this scene needs. If any are absent, offer to import the package.
function resolveAssets() {
    var missing = [];
    var i;
    for (i = 0; i < REQUIRED.length; i++) {
        if (findComp(REQUIRED[i]) === null) { missing.push(REQUIRED[i]); }
    }
    if (missing.length === 0) { return true; }

    var answer = confirm(missing.length + " asset comp(s) are not in this project.\\n\\n" +
                         "Locate Win95Assets.aep to import the asset package?");
    if (!answer) { return false; }

    var aep = File.openDialog("Select Win95Assets.aep", "After Effects Project:*.aep");
    if (aep === null) { return false; }

    var io = new ImportOptions(aep);
    io.importAs = ImportAsType.PROJECT;   // lands as a folder holding every comp
    app.project.importFile(io);
    log("imported package from " + aep.fsName);

    missing = [];
    for (i = 0; i < REQUIRED.length; i++) {
        if (findComp(REQUIRED[i]) === null) { missing.push(REQUIRED[i]); }
    }
    if (missing.length > 0) {
        alert("Still missing after import:\\n" + missing.join("\\n") +
              "\\n\\nRe-export the asset package so it includes these.");
        return false;
    }
    return true;
}

function buildWindowComp(folder, win, font) {
    var comp = app.project.items.addComp("Window - " + win.title, win.w, win.h, 1.0, SCENE.fps, SCENE.duration);
    comp.parentFolder = folder;

    // Frame, bevels, title bar and button faces: one shape layer, one group per colour.
    var chrome = addShapeLayer(comp, "Chrome");
    var contents = contentsOf(chrome);
    for (var i = 0; i < win.frame.length; i++) {
        addColorGroup(contents, win.frame[i].k, win.frame[i].c, win.frame[i].r);
    }

    // The close glyph, offset to the button's position.
    var glyph = addShapeLayer(comp, "Close glyph");
    var gc = contentsOf(glyph);
    var moved = [];
    for (var g = 0; g < win.glyph.r.length; g++) {
        var r = win.glyph.r[g];
        moved.push([r[0] + win.glyph.x, r[1] + win.glyph.y, r[2], r[3]]);
    }
    addColorGroup(gc, "glyph", GLYPH_RGB, moved);

    // Title bar icon: a layer referencing the package comp, so the asset stays independent.
    if (win.icon !== null) {
        var iconComp = findComp(win.icon);
        if (iconComp !== null) {
            var iconLayer = comp.layers.add(iconComp);
            iconLayer.name = win.icon;
            iconLayer.property("ADBE Transform Group").property("ADBE Position")
                .setValue(centreOf(win.iconPos.x, win.iconPos.y, iconComp.width, iconComp.height));
        }
    }

    addTextLayer(comp, win.title, FONT_PS, font, TITLE_SIZE, TITLE_RGB, win.textX, win.textBaseline);
    return comp;
}

function main() {
    var started = new Date();
    if (!resolveAssets()) { return; }

    app.beginUndoGroup("Build Win95 scene");
    var suppressed = suppressRefresh(true);
    var font = findFont(FONT_PS);
    log("scene build; app.version=" + app.version + " font=" + (font === null ? "NOT FOUND (" + FONT_PS + ")" : "ok"));

    var root = findFolder("Win95 Scenes");
    if (root === null) { root = app.project.items.addFolder("Win95 Scenes"); }
    var sceneFolder = app.project.items.addFolder(SCENE.name);
    sceneFolder.parentFolder = root;
    var winFolder = app.project.items.addFolder("Windows");
    winFolder.parentFolder = sceneFolder;

    var scene = app.project.items.addComp("Scene - " + SCENE.name, SCENE.w, SCENE.h, 1.0, SCENE.duration, SCENE.fps);
    scene.parentFolder = sceneFolder;

    // Desktop background, locked so it is never dragged by accident.
    var desk = scene.layers.addSolid(SCENE.bg, "Desktop", SCENE.w, SCENE.h, 1.0);
    desk.locked = true;

    // Placed icons, each referencing its package comp.
    var i;
    for (i = 0; i < ICONS.length; i++) {
        var spec = ICONS[i];
        var assetComp = findComp(spec.comp);
        if (assetComp === null) { log("MISSING " + spec.comp); continue; }
        var layer = scene.layers.add(assetComp);
        layer.name = spec.comp;
        layer.property("ADBE Transform Group").property("ADBE Position")
            .setValue(centreOf(spec.x, spec.y, assetComp.width, assetComp.height));
        layer.comment = "icon:" + spec.comp;
        if (spec.label !== "") {
            addTextLayer(scene, spec.label, FONT_PS, font, TITLE_SIZE, TITLE_RGB,
                         spec.x, spec.y + assetComp.height + 12);
        }
    }

    // Windows, back to front: WINDOWS is already sorted by z ascending, and each new layer
    // lands on top of the previous one, so the stack matches the scene with no reordering.
    for (i = 0; i < WINDOWS.length; i++) {
        var win = WINDOWS[i];
        var winComp = buildWindowComp(winFolder, win, font);
        var winLayer = scene.layers.add(winComp);
        winLayer.name = win.title;
        winLayer.property("ADBE Transform Group").property("ADBE Position")
            .setValue(centreOf(win.x, win.y, win.w, win.h));
        winLayer.comment = "window:" + win.id;
        winLayer.moveToBeginning();
    }

    if (SCENE.taskbar) {
        var bar = addShapeLayer(scene, "Taskbar");
        addColorGroup(contentsOf(bar), "face", TASKBAR_RGB,
                      [[0, SCENE.h - TASKBAR_H, SCENE.w, TASKBAR_H]]);
        bar.moveToBeginning();
    }

    if (suppressed) { suppressRefresh(false); }
    app.endUndoGroup();
    scene.openInViewer();

    log("done in " + ((new Date()).getTime() - started.getTime()) + " ms");
}

try { main(); }
catch (err) { alert("Scene export FAILED\\n" + err.toString() + "\\nline " + err.line + "\\n\\n" + LOG.join("\\n")); }
`
}
