/**
 * The two ExtendScript generators.
 *
 * The split is the one Kyle asked for, and it is a build/link split rather than two unrelated
 * exporters:
 *
 *   PACKAGE  every catalogue asset becomes its own comp, saved once into a standalone
 *            `Win95Assets.aep`. Expensive, run rarely.
 *   SCENE    a layout becomes a scene comp whose layers *reference* comps from that package.
 *            Cheap, run constantly.
 *
 * The mechanism underneath is `project.save(file)` on one side and `importFile` with
 * `ImportAsType.PROJECT` on the other — the AE spike proved that round trip: a saved `.aep`
 * re-imports into a different project as a single folder containing every comp intact.
 *
 * Both scripts are ES3, both embed their data as object literals (there is no `JSON` in
 * ExtendScript), and both share `ES3_RUNTIME`.
 */

import { toRgb } from '../assets/colors'
import { mergeRuns, parseRuns } from '../assets/svgPath'
import {
  CLOSE_GLYPH,
  WINDOW_CHROME,
  WIN95_COLORS,
  WIN95_FONT,
  closeButtonRects,
  windowFrameRects,
  type ChromeRect,
} from '../assets/chrome'
import type { IconGeometry } from '../assets/iconGeometry'
import type { Scene } from '../scene/types'
import { es3Literal, type Es3Value } from './es3'
import { ES3_RUNTIME } from './runtime'

/** Comp name for a catalogue asset. The scene script resolves package comps by this exact name. */
export function assetCompName(assetId: string): string {
  return `Icon - ${assetId}`
}

/** Folder the package builds into, and the folder the scene script looks inside. */
export const PACKAGE_FOLDER = 'Win95 Assets'

/** Rectangles grouped by colour, in the compact shape the ES3 runtime consumes. */
type EmittedLayer = { k: string; c: readonly number[]; r: number[][] }

function emitChromeLayers(rects: ChromeRect[]): EmittedLayer[] {
  // One AE group per colour rather than per rectangle: far fewer groups, and it matches how the
  // icon geometry is already organised, so the runtime needs only one code path.
  const byColor = new Map<string, number[][]>()
  for (const rect of rects) {
    const bucket = byColor.get(rect.color)
    if (bucket) bucket.push([rect.x, rect.y, rect.w, rect.h])
    else byColor.set(rect.color, [[rect.x, rect.y, rect.w, rect.h]])
  }
  return [...byColor.entries()].map(([color, r]) => ({ k: color, c: toRgb(color), r }))
}

function emitIconLayers(icon: IconGeometry): EmittedLayer[] {
  return icon.layers.map((layer) => ({
    k: layer.color,
    c: toRgb(layer.color),
    r: layer.rects.map((rect) => [rect.x, rect.y, rect.w, rect.h]),
  }))
}

function header(title: string, extra: string[] = []): string {
  const lines = [
    `// ${title}`,
    '//',
    '// Generated by the Windows 95 Asset Studio. Do not edit by hand - re-export instead.',
    `// Generated ${new Date().toISOString()}`,
    '//',
    ...extra.map((line) => `// ${line}`),
    '',
    '#target aftereffects',
  ]
  return lines.join('\n')
}

// ---------------------------------------------------------------------------- package

/**
 * How an asset's artwork is represented in the package.
 *
 * `png` — import the icon's PNG as footage and wrap it in a comp. **Pixel-exact and fast.**
 * `shapes` — rebuild the artwork as AE shape rectangles. Editable vector, but neither exact nor
 * fast at scale.
 *
 * Both were measured against the package's own PNG as ground truth, rendering each through
 * `CompItem.saveFrameToPng` in After Effects 27.0 and comparing pixels:
 *
 *   format   differing px   partial-alpha px   distinct colours (source has 7)   import/build
 *   png      0 / 256        0                  7                                 110 items/s
 *   shapes   99 / 256       21                 31                                see below
 *   svg      74 / 256       21                 48                                63 items/s
 *
 * The geometry fed to the shape builder is provably correct — painting the emitted rectangles
 * onto a grid reproduces the reference PNG exactly, with zero overlaps. After Effects renders
 * *simple* shape rectangles on integer boundaries perfectly crisply (verified), but blends the
 * dense interlocking runs a real icon is made of. So the loss is in AE's shape rasteriser, not
 * in this code.
 *
 * Shape building is also superlinear: 7,033 shapes took 19.5 s, 21,084 took 247 s — 3x the work
 * for 12.7x the time — and produced a 30 MB project for 200 icons. The full catalogue projects
 * to hours and hundreds of megabytes.
 *
 * Hence `png` is the default. `shapes` stays available because vector artwork is editable and
 * recolourable in After Effects, which matters for a handful of hand-picked assets even though
 * it is the wrong representation for the whole catalogue.
 */
export type PackageFormat = 'png' | 'shapes'

export type PackageOptions = {
  /** Artwork representation. Defaults to `png` — see PackageFormat for the measurements. */
  format?: PackageFormat
  /**
   * Directory holding the source PNGs (`@react95/icons/png`). Required for `png` format. The
   * script copies what it needs into `<output>/assets/` and imports from there, so the finished
   * package folder is portable and does not reference node_modules.
   */
  pngSourceDir?: string
  /** Comp frame rate and duration. Static assets still need both. */
  fps?: number
  durationSeconds?: number
  /** File name written into the chosen folder. */
  fileName?: string
  /** Comps per undo group. Batching is what keeps a large build from exhausting memory. */
  undoBatch?: number
  /** How often to flush a progress line to the log during a long build. */
  progressEvery?: number
  /**
   * Absolute folder to save into. When set, the script runs **unattended**: no folder picker and
   * no final alert, just the log file.
   *
   * This exists because a modal dialog is fatal to `AfterFX.com -r`, which is how the local
   * companion will drive After Effects — the script would sit forever on a dialog nobody is
   * looking at. It is also what makes the export testable at all without a human clicking
   * through it.
   */
  outputPath?: string
}

/**
 * The default package: every asset's PNG copied beside the `.aep`, imported as footage, and
 * wrapped in a comp of exactly its own size.
 *
 * No deduplication here, unlike the shape route. Importing a footage item is cheap (measured at
 * 110/second), so collapsing the ~480 duplicate images would save a second or two and cost the
 * alias machinery. Every name simply gets its own footage item and its own comp.
 *
 * The files are copied rather than referenced in place because After Effects stores footage
 * paths in the project: referencing `node_modules` would produce an `.aep` that breaks the
 * moment the repo moves or someone else opens it. After the copy, the package folder — `.aep`
 * plus `assets/` — moves as a unit, which is what research note 02 assumed for footage.
 */
function buildPngPackageScript(icons: IconGeometry[], options: PackageOptions): string {
  const fps = options.fps ?? 30
  const duration = options.durationSeconds ?? 10
  const fileName = options.fileName ?? 'Win95Assets.aep'
  // `null` means "look next to the script itself". The studio's browser export has no
  // filesystem path to hand over — it ships the PNGs in a zip beside the .jsx — so the script
  // resolves its own location at run time via $.fileName. A caller that does know the path (the
  // companion, or a Node build) passes it and skips the guessing.
  const source = options.pngSourceDir ?? null

  const assets: Es3Value = icons.map((icon) => ({
    n: assetCompName(icon.asset.id),
    f: `${icon.asset.id}.png`,
  }))

  return `${header('Windows 95 asset package - every asset as its own comp', [
    `${icons.length} assets as PNG footage, each wrapped in its own comp`,
    '',
    'Pixel-exact: the artwork is the icon set\'s own PNG, imported 1:1 and never scaled.',
    'The PNGs are copied into an "assets" folder beside the .aep, so the package folder',
    'moves as a unit. Keep them together.',
    '',
    'Run: File > Scripts > Run Script File, then choose an output folder.',
  ])}

${ES3_RUNTIME}

var FPS = ${fps};
var DURATION = ${duration};
var FILENAME = ${es3Literal(fileName)};
var FOLDER_NAME = ${es3Literal(PACKAGE_FOLDER)};
// null = the "assets" folder beside this script, which is how the zipped browser export is laid
// out. $.fileName is ExtendScript's path to the running script.
var PNG_SOURCE = ${source === null ? 'null' : es3Literal(source)};
if (PNG_SOURCE === null) {
    PNG_SOURCE = new File($.fileName).parent.fsName + "/assets";
}
var OUTPUT_PATH = ${options.outputPath === undefined ? 'null' : es3Literal(options.outputPath)};
var LOG_DIR = ${options.outputPath === undefined ? 'null' : es3Literal(options.outputPath)};
var UNDO_BATCH = ${options.undoBatch ?? 50};
var PROGRESS_EVERY = ${options.progressEvery ?? 200};

// n = comp name, f = file name inside the source directory.
var ASSETS = ${es3Literal(assets)};

function main() {
    var started = new Date();
    var outDir;
    if (OUTPUT_PATH === null) {
        outDir = Folder.selectDialog("Choose a folder to save " + FILENAME + " into");
        if (outDir === null) { return; }
    } else {
        outDir = new Folder(OUTPUT_PATH);
        if (!outDir.exists && !outDir.create()) { throw new Error("Cannot create " + OUTPUT_PATH); }
    }

    var assetDir = new Folder(outDir.fsName + "/assets");
    if (!assetDir.exists && !assetDir.create()) { throw new Error("Cannot create assets folder"); }

    app.newProject();
    var suppressed = (OUTPUT_PATH !== null) && suppressDialogs(true);
    log("png package build " + started.toString());
    log("app.version=" + app.version + " suppressDialogs=" + suppressed);

    var root = app.project.items.addFolder(FOLDER_NAME);
    var icons = app.project.items.addFolder("Icons");
    icons.parentFolder = root;

    var built = 0, missing = 0;
    var checkpoint = started.getTime();

    // Batched undo groups for the same reason as the shape route: one group spanning the whole
    // build retains every operation and grows without bound.
    for (var i = 0; i < ASSETS.length; i++) {
        if (i % UNDO_BATCH === 0) {
            if (i > 0) { app.endUndoGroup(); }
            app.beginUndoGroup("Win95 assets " + i);
        }
        var file = copyAsset(PNG_SOURCE, assetDir, ASSETS[i].f);
        if (file === null) { log("MISSING source " + ASSETS[i].f); missing++; continue; }
        buildFootageComp(icons, ASSETS[i].n, file, FPS, DURATION);
        built++;

        if (i > 0 && i % PROGRESS_EVERY === 0) {
            var now = (new Date()).getTime();
            log("  " + i + "/" + ASSETS.length + " comps, +" + (now - checkpoint) + " ms");
            checkpoint = now;
            if (LOG_DIR !== null) { writeLog(new Folder(LOG_DIR), "win95-package-progress.txt"); }
        }
    }
    if (ASSETS.length > 0) { app.endUndoGroup(); }
    log("built " + built + " comps, " + missing + " missing sources");

    if (suppressed) { suppressDialogs(false); }

    var aep = new File(outDir.fsName + "/" + FILENAME);
    app.project.save(aep);

    var ms = (new Date()).getTime() - started.getTime();
    log("saved " + aep.fsName + " (" + aep.length + " bytes) in " + ms + " ms");
    log("comps per second: " + (built / (ms / 1000)).toFixed(1));
    writeLog(outDir, "win95-package-log.txt");

    if (OUTPUT_PATH === null) {
        alert("Asset package built.\\n\\n" + built + " comps in " + Math.round(ms / 1000) + " s\\n\\n" +
              aep.fsName + "\\n\\nKeep the 'assets' folder beside it.");
    }
}

try { main(); }
catch (err) {
    log("FAILED " + err.toString() + " line " + err.line);
    if (OUTPUT_PATH === null) {
        alert("Package export FAILED\\n" + err.toString() + "\\nline " + err.line);
    } else {
        writeLog(new Folder(OUTPUT_PATH), "win95-package-log.txt");
    }
}
`
}

/**
 * The shape-based package: artwork rebuilt as AE shape rectangles, editable as vector.
 *
 * Not the default — see `PackageFormat` for the measured fidelity and speed against `png`. Use
 * it for a handful of assets you intend to recolour or edit in After Effects, not for the
 * catalogue.
 *
 * The geometry has already been merged from pixel runs into rectangles (~30% fewer shapes,
 * losslessly), and identical artwork is drawn once — 1517 drawable entries reduce to 1037
 * distinct images, because @react95/icons ships the same bitmap under several names. Aliases get
 * a one-layer comp so every catalogue name still resolves.
 */
export function buildPackageScript(icons: IconGeometry[], options: PackageOptions = {}): string {
  const format = options.format ?? 'png'
  if (format === 'png') return buildPngPackageScript(icons, options)

  const fps = options.fps ?? 30
  const duration = options.durationSeconds ?? 10
  const fileName = options.fileName ?? 'Win95Assets.aep'

  // Deduplicate by geometry. @react95/icons ships a lot of the same artwork under different
  // names — 1517 drawable entries reduce to 1037 distinct images — so one comp can hold the
  // shapes for all of its names.
  //
  // The alias map is keyed and valued by **comp name**, not asset id. That matters: the scene
  // script resolves everything by comp name, and if an alias pointed at a bare asset id the
  // package would build a comp the scene could never find. Every catalogue name still ends up
  // with its own comp (see the alias-comp loop in the script) — the geometry is shared, the
  // identity is not.
  const seen = new Map<string, string>() // signature -> comp name that owns the geometry
  const unique: IconGeometry[] = []
  const aliases: Record<string, string> = {}

  for (const icon of icons) {
    const signature = JSON.stringify(emitIconLayers(icon))
    const owner = seen.get(signature)
    if (owner) {
      aliases[assetCompName(icon.asset.id)] = owner
    } else {
      seen.set(signature, assetCompName(icon.asset.id))
      unique.push(icon)
    }
  }

  const assets: Es3Value = unique.map((icon) => ({
    n: assetCompName(icon.asset.id),
    w: icon.asset.width,
    h: icon.asset.height,
    l: emitIconLayers(icon) as unknown as Es3Value,
  }))

  const totalShapes = unique.reduce((sum, icon) => sum + icon.shapeCount, 0)

  return `${header('Windows 95 asset package - every asset as its own comp', [
    `${icons.length} catalogue assets -> ${unique.length} comps (${
      icons.length - unique.length
    } are duplicate artwork)`,
    `${totalShapes} shape rectangles after lossless run merging`,
    '',
    'Run: File > Scripts > Run Script File, then choose an output folder.',
    'This builds into a NEW project and saves the .aep; your open project is left alone',
    '(you will be prompted to save it if it has unsaved changes).',
  ])}

${ES3_RUNTIME}

var FPS = ${fps};
var DURATION = ${duration};
var FILENAME = ${es3Literal(fileName)};
var FOLDER_NAME = ${es3Literal(PACKAGE_FOLDER)};
// null = ask for a folder and report with an alert. A path = run unattended, for AfterFX.com -r.
var OUTPUT_PATH = ${options.outputPath === undefined ? 'null' : es3Literal(options.outputPath)};
// Comps per undo group. See the loop below for why this must not be the whole build.
var UNDO_BATCH = ${options.undoBatch ?? 25};
var PROGRESS_EVERY = ${options.progressEvery ?? 50};
// Where progress is flushed during a long build. Only set for unattended runs.
var LOG_DIR = ${options.outputPath === undefined ? 'null' : es3Literal(options.outputPath)};

// Every asset: n = comp name, w/h = size, l = one entry per colour with pre-computed RGB.
var ASSETS = ${es3Literal(assets)};

// Comp name -> comp name whose artwork is byte-identical. Each of these still gets its own
// comp; it just holds one layer of the shared original instead of its own copy of the shapes.
var ALIASES = ${es3Literal(aliases as unknown as Es3Value)};

function main() {
    var started = new Date();
    var outDir;
    if (OUTPUT_PATH === null) {
        outDir = Folder.selectDialog("Choose a folder to save " + FILENAME + " into");
        if (outDir === null) { return; }
    } else {
        outDir = new Folder(OUTPUT_PATH);
        if (!outDir.exists && !outDir.create()) {
            throw new Error("Cannot create output folder " + OUTPUT_PATH);
        }
    }

    // Discards whatever is open. In unattended mode this must never surprise anyone, so the
    // caller is responsible for having confirmed it -- the studio's UI does, and the companion
    // will have to.
    app.newProject();
    var suppressed = (OUTPUT_PATH !== null) && suppressDialogs(true);

    log("package build " + started.toString());
    log("app.version=" + app.version + " suppressDialogs=" + suppressed);

    var root = app.project.items.addFolder(FOLDER_NAME);
    var icons = app.project.items.addFolder("Icons");
    icons.parentFolder = root;

    // Keep the built comps in a lookup as we go. Scanning app.project.items for each alias
    // would be O(aliases x items) -- around 500 x 1500 on a full catalogue build.
    var byName = {};
    var shapes = 0;
    var checkpoint = started.getTime();

    // ONE UNDO GROUP PER BATCH, NOT ONE FOR THE WHOLE BUILD.
    //
    // Wrapping the entire build in a single beginUndoGroup made a full-catalogue run unusable:
    // 27 minutes in, After Effects had burned 2000 s of CPU and 3.3 GB of memory and still had
    // not finished, against a linear projection of under 5 minutes from a small run. Everything
    // done inside a group is retained so the group can be undone as one action, so a group
    // holding ~146,000 shape additions grows without bound.
    //
    // After Effects keeps a bounded number of undo levels (32 by default), so many small groups
    // let old ones fall off the end and their memory be released. Undo granularity costs nothing
    // here: a package build starts at app.newProject() and ends at a saved .aep, so there is
    // nothing a user would ever want to step back through.
    for (var i = 0; i < ASSETS.length; i++) {
        if (i % UNDO_BATCH === 0) {
            if (i > 0) { app.endUndoGroup(); }
            app.beginUndoGroup("Win95 assets " + i);
        }
        var built = buildAssetComp(icons, ASSETS[i], FPS, DURATION);
        byName[ASSETS[i].n] = built.comp;
        shapes += built.shapes;

        // Progress into the log, so a long build can be watched from outside After Effects
        // instead of guessed at. This is also what turns a hang into a diagnosable slowdown.
        if (i > 0 && i % PROGRESS_EVERY === 0) {
            var now = (new Date()).getTime();
            log("  " + i + "/" + ASSETS.length + " comps, " + shapes + " shapes, +" +
                (now - checkpoint) + " ms");
            checkpoint = now;
            if (LOG_DIR !== null) { writeLog(new Folder(LOG_DIR), "win95-package-progress.txt"); }
        }
    }
    if (ASSETS.length > 0) { app.endUndoGroup(); }
    log("built " + ASSETS.length + " comps, " + shapes + " shapes");

    // Every duplicate name still gets its own comp, holding a single layer of the original.
    // That costs one comp and one layer instead of re-drawing the shapes, and it means the
    // scene script can resolve any catalogue name without knowing aliasing exists.
    // Batched for the same reason as the loop above, though ~500 one-layer comps is far lighter
    // than the shape building.
    var aliasCount = 0;
    for (var key in ALIASES) {
        if (!ALIASES.hasOwnProperty(key)) { continue; }
        var owner = byName[ALIASES[key]];
        if (owner === undefined) { log("alias owner missing: " + ALIASES[key]); continue; }
        if (aliasCount % UNDO_BATCH === 0) {
            if (aliasCount > 0) { app.endUndoGroup(); }
            app.beginUndoGroup("Win95 aliases " + aliasCount);
        }
        var aliasComp = app.project.items.addComp(key, owner.width, owner.height, 1.0, DURATION, FPS);
        aliasComp.parentFolder = icons;
        aliasComp.layers.add(owner).name = ALIASES[key];
        aliasCount++;
    }
    // Only if a group was actually opened: with no aliases the loop opens none, and a stray
    // endUndoGroup would be unbalanced.
    if (aliasCount > 0) { app.endUndoGroup(); }
    log("aliases: " + aliasCount + " names share artwork via a one-layer comp");

    if (suppressed) { suppressDialogs(false); }

    var aep = new File(outDir.fsName + "/" + FILENAME);
    app.project.save(aep);

    var ms = (new Date()).getTime() - started.getTime();
    log("saved " + aep.fsName + " (" + aep.length + " bytes) in " + ms + " ms");
    log("shapes per second: " + Math.round(shapes / (ms / 1000)));
    writeLog(outDir, "win95-package-log.txt");

    if (OUTPUT_PATH === null) {
        alert("Asset package built.\\n\\n" +
              ASSETS.length + " comps + " + aliasCount + " aliases, " + shapes + " shapes\\n" +
              Math.round(ms / 1000) + " seconds\\n\\n" +
              aep.fsName +
              "\\n\\nImport this into any project with File > Import > File.");
    }
}

// An unattended run must never leave a modal dialog up: AfterFX.com -r returns immediately and
// nobody is watching After Effects to dismiss it. Failures go to the log instead, and the caller
// finds out because the .aep it expected is not there.
try { main(); }
catch (err) {
    log("FAILED " + err.toString() + " line " + err.line);
    if (OUTPUT_PATH === null) {
        alert("Package export FAILED\\n" + err.toString() + "\\nline " + err.line + "\\n\\n" + LOG.join("\\n"));
    } else {
        writeLog(new Folder(OUTPUT_PATH), "win95-package-log.txt");
    }
}
`
}

// ---------------------------------------------------------------------------- scene

export type SceneOptions = {
  /**
   * Assets the scene needs, so the script can name precisely what is missing when the package
   * has not been imported yet.
   */
  requiredAssetIds: string[]
  /**
   * Absolute path to `Win95Assets.aep`. When set the script imports it without asking and never
   * shows a dialog, so it can run under `AfterFX.com -r`. When absent it prompts, which is the
   * right behaviour for a script a human ran from File > Scripts.
   */
  packagePath?: string
  /** Where to write the run log when running unattended. */
  logPath?: string
  /**
   * Absolute path of an `.aep` to save the finished scene into.
   *
   * When set, the script starts from `app.newProject()` and saves at the end, so what comes out
   * is a standalone project file at a path the user chose rather than comps added to whatever
   * happened to be open. That is the companion's whole job — "set this up in an After Effects
   * file for me" — and it is deliberately not the default, because a script a human ran from
   * File > Scripts should add to the project they are looking at, not replace it.
   */
  projectPath?: string
}

/**
 * Build the scene script: window precomps drawn from the chrome registry, plus layers that
 * reference the package's asset comps.
 *
 * Window comps are built here rather than pre-baked into the package because their geometry
 * depends on the size the user dragged them to — a package cannot enumerate every possible
 * window size. Their title-bar icons still reference package comps, so "every asset is its own
 * comp" holds throughout.
 */
export function buildSceneScript(scene: Scene, options: SceneOptions): string {
  const closeGlyphRects = mergeRuns(parseRuns(CLOSE_GLYPH)).map((r) => [r.x, r.y, r.w, r.h])

  // Windows are emitted back-to-front so the script can add layers in order and let each new
  // layer land on top, which avoids any moveBefore/moveAfter juggling.
  const windows = [...scene.windows].sort((a, b) => a.z - b.z)

  const emittedWindows: Es3Value = windows.map((win) => {
    const button = closeButtonRects(win.width)
    return {
      id: win.id,
      title: win.title,
      icon: win.iconAssetId ? assetCompName(win.iconAssetId) : null,
      x: win.x,
      y: win.y,
      w: win.width,
      h: win.height,
      // Frame and button share one shape layer per colour group.
      frame: emitChromeLayers([...windowFrameRects(win.width, win.height, win.active), ...button.rects]) as unknown as Es3Value,
      glyph: { x: button.glyph.x, y: button.glyph.y, r: closeGlyphRects },
      iconPos: { x: WINDOW_CHROME.iconOffset.x, y: WINDOW_CHROME.iconOffset.y },
      textX: WINDOW_CHROME.titleTextX,
      textBaseline: WINDOW_CHROME.titleBaselineY,
    }
  })

  const emittedIcons: Es3Value = scene.icons.map((icon) => ({
    comp: assetCompName(icon.assetId),
    x: icon.x,
    y: icon.y,
    label: icon.label,
  }))

  return `${header(`Windows 95 scene - ${scene.name}`, [
    `${scene.windows.length} windows, ${scene.icons.length} placed icons`,
    `${scene.width}x${scene.height} @ ${scene.fps}fps`,
    '',
    'Requires the asset package. Import Win95Assets.aep first, or let this script',
    'prompt you for it. Run with File > Scripts > Run Script File.',
  ])}

${ES3_RUNTIME}

var SCENE = ${es3Literal({
    name: scene.name,
    w: scene.width,
    h: scene.height,
    fps: scene.fps,
    duration: scene.durationSeconds,
    bg: [...toRgb(scene.background)],
    taskbar: scene.showTaskbar,
  } as unknown as Es3Value)};

var FONT_PS = ${es3Literal(WIN95_FONT.postScriptName)};
var TITLE_SIZE = ${WIN95_FONT.titleSize};
var TITLE_RGB = ${es3Literal([...toRgb(WIN95_COLORS.titleText)] as unknown as Es3Value)};
var GLYPH_RGB = ${es3Literal([...toRgb(WIN95_COLORS.darkest)] as unknown as Es3Value)};
var TASKBAR_RGB = ${es3Literal([...toRgb(WIN95_COLORS.face)] as unknown as Es3Value)};
var TASKBAR_H = 28;

var WINDOWS = ${es3Literal(emittedWindows)};
var ICONS = ${es3Literal(emittedIcons)};
var REQUIRED = ${es3Literal(options.requiredAssetIds.map(assetCompName) as unknown as Es3Value)};
// Set = run unattended (import this package, no dialogs). null = ask.
var PACKAGE_PATH = ${options.packagePath === undefined ? 'null' : es3Literal(options.packagePath)};
var LOG_PATH = ${options.logPath === undefined ? 'null' : es3Literal(options.logPath)};
// Set = start from a new project and save the result here. null = add to the open project.
var PROJECT_PATH = ${options.projectPath === undefined ? 'null' : es3Literal(options.projectPath)};

// Resolve every asset comp this scene needs. If any are absent, import the package.
function resolveAssets() {
    var missing = [];
    var i;
    for (i = 0; i < REQUIRED.length; i++) {
        if (findComp(REQUIRED[i]) === null) { missing.push(REQUIRED[i]); }
    }
    if (missing.length === 0) { return true; }

    var aep;
    if (PACKAGE_PATH !== null) {
        aep = new File(PACKAGE_PATH);
        if (!aep.exists) { log("package not found at " + PACKAGE_PATH); return false; }
    } else {
        var answer = confirm(missing.length + " asset comp(s) are not in this project.\\n\\n" +
                             "Locate Win95Assets.aep to import the asset package?");
        if (!answer) { return false; }
        aep = File.openDialog("Select Win95Assets.aep", "After Effects Project:*.aep");
        if (aep === null) { return false; }
    }

    var io = new ImportOptions(aep);
    io.importAs = ImportAsType.PROJECT;   // lands as a folder holding every comp
    app.project.importFile(io);
    log("imported package from " + aep.fsName);

    missing = [];
    for (i = 0; i < REQUIRED.length; i++) {
        if (findComp(REQUIRED[i]) === null) { missing.push(REQUIRED[i]); }
    }
    if (missing.length > 0) {
        log("still missing after import: " + missing.join(", "));
        if (PACKAGE_PATH === null) {
            alert("Still missing after import:\\n" + missing.join("\\n") +
                  "\\n\\nRe-export the asset package so it includes these.");
        }
        return false;
    }
    return true;
}

function buildWindowComp(folder, win, font) {
    var comp = app.project.items.addComp("Window - " + win.title, win.w, win.h, 1.0, SCENE.fps, SCENE.duration);
    comp.parentFolder = folder;

    // Frame, bevels, title bar and button faces: one shape layer, one group per colour.
    var chrome = addShapeLayer(comp, "Chrome");
    var contents = contentsOf(chrome);
    for (var i = 0; i < win.frame.length; i++) {
        addColorGroup(contents, win.frame[i].k, win.frame[i].c, win.frame[i].r);
    }

    // The close glyph, offset to the button's position.
    var glyph = addShapeLayer(comp, "Close glyph");
    var gc = contentsOf(glyph);
    var moved = [];
    for (var g = 0; g < win.glyph.r.length; g++) {
        var r = win.glyph.r[g];
        moved.push([r[0] + win.glyph.x, r[1] + win.glyph.y, r[2], r[3]]);
    }
    addColorGroup(gc, "glyph", GLYPH_RGB, moved);

    // Title bar icon: a layer referencing the package comp, so the asset stays independent.
    if (win.icon !== null) {
        var iconComp = findComp(win.icon);
        if (iconComp !== null) {
            var iconLayer = comp.layers.add(iconComp);
            iconLayer.name = win.icon;
            iconLayer.property("ADBE Transform Group").property("ADBE Position")
                .setValue(centreOf(win.iconPos.x, win.iconPos.y, iconComp.width, iconComp.height));
        }
    }

    addTextLayer(comp, win.title, FONT_PS, font, TITLE_SIZE, TITLE_RGB, win.textX, win.textBaseline);
    return comp;
}

function main() {
    var started = new Date();
    // Before resolveAssets, which imports the package into whatever project is current. Doing
    // this after would import into the user's project and then throw it away.
    if (PROJECT_PATH !== null) { app.newProject(); }
    if (!resolveAssets()) { return; }

    app.beginUndoGroup("Build Win95 scene");
    var suppressed = (LOG_PATH !== null) && suppressDialogs(true);
    var font = findFont(FONT_PS);
    log("scene build; app.version=" + app.version + " font=" + (font === null ? "NOT FOUND (" + FONT_PS + ")" : "ok"));

    var root = findFolder("Win95 Scenes");
    if (root === null) { root = app.project.items.addFolder("Win95 Scenes"); }
    var sceneFolder = app.project.items.addFolder(SCENE.name);
    sceneFolder.parentFolder = root;
    var winFolder = app.project.items.addFolder("Windows");
    winFolder.parentFolder = sceneFolder;

    var scene = app.project.items.addComp("Scene - " + SCENE.name, SCENE.w, SCENE.h, 1.0, SCENE.duration, SCENE.fps);
    scene.parentFolder = sceneFolder;

    // Desktop background, locked so it is never dragged by accident.
    var desk = scene.layers.addSolid(SCENE.bg, "Desktop", SCENE.w, SCENE.h, 1.0);
    desk.locked = true;

    // Placed icons, each referencing its package comp.
    var i;
    for (i = 0; i < ICONS.length; i++) {
        var spec = ICONS[i];
        var assetComp = findComp(spec.comp);
        if (assetComp === null) { log("MISSING " + spec.comp); continue; }
        var layer = scene.layers.add(assetComp);
        layer.name = spec.comp;
        layer.property("ADBE Transform Group").property("ADBE Position")
            .setValue(centreOf(spec.x, spec.y, assetComp.width, assetComp.height));
        layer.comment = "icon:" + spec.comp;
        if (spec.label !== "") {
            addTextLayer(scene, spec.label, FONT_PS, font, TITLE_SIZE, TITLE_RGB,
                         spec.x, spec.y + assetComp.height + 12);
        }
    }

    // Windows, back to front: WINDOWS is already sorted by z ascending, and each new layer
    // lands on top of the previous one, so the stack matches the scene with no reordering.
    for (i = 0; i < WINDOWS.length; i++) {
        var win = WINDOWS[i];
        var winComp = buildWindowComp(winFolder, win, font);
        var winLayer = scene.layers.add(winComp);
        winLayer.name = win.title;
        winLayer.property("ADBE Transform Group").property("ADBE Position")
            .setValue(centreOf(win.x, win.y, win.w, win.h));
        winLayer.comment = "window:" + win.id;
        winLayer.moveToBeginning();
    }

    if (SCENE.taskbar) {
        var bar = addShapeLayer(scene, "Taskbar");
        addColorGroup(contentsOf(bar), "face", TASKBAR_RGB,
                      [[0, SCENE.h - TASKBAR_H, SCENE.w, TASKBAR_H]]);
        bar.moveToBeginning();
    }

    if (suppressed) { suppressDialogs(false); }
    app.endUndoGroup();
    scene.openInViewer();

    // The finished project, at the path the user browsed to. Saved after endUndoGroup so the
    // file on disk is the completed scene rather than a half-built one.
    if (PROJECT_PATH !== null) {
        var out = new File(PROJECT_PATH);
        if (out.parent !== null && !out.parent.exists) { out.parent.create(); }
        app.project.save(out);
        log("saved " + out.fsName + " (" + out.length + " bytes)");
    }

    log("done in " + ((new Date()).getTime() - started.getTime()) + " ms");
}

// Same rule as the package script: unattended runs write a log, never a modal dialog.
function finish() {
    if (LOG_PATH !== null) { writeLog(new Folder(LOG_PATH), "win95-scene-log.txt"); }
}

try { main(); finish(); }
catch (err) {
    log("FAILED " + err.toString() + " line " + err.line);
    finish();
    if (LOG_PATH === null) {
        alert("Scene export FAILED\\n" + err.toString() + "\\nline " + err.line + "\\n\\n" + LOG.join("\\n"));
    }
}
`
}
